### ISSUE TITLE
Core dump when trying to list all or local scanner devices

### ISSUE THREAD

**Issue by chuckremes** [sglass68/paperman#11]
OS: Ubuntu 16.10
`Linux remes-linux 4.8.0-39-generic #42-Ubuntu SMP Mon Feb 20 11:47:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

What did I do?
I built paperman from current master (f50d0072b55) according to INSTALL instructions. Ran `./paperman`. Clicked on "Perform a scan immediately using current settings" which brought up a dialog box to pick a device. I first clicked on "select all devices" which core dumped. I then reran and tried "select local devices" and it cored too.

What was the output?
Here's a gist with the entire backtrace. If you'd like me to run this under gdb/lldb and get more information, let me know.
https://gist.github.com/chuckremes/2eb32fbc1d982a6fe59a5b875778e6ff

**Comment by chuckremes** [comment]
Since I offered a gdb backtrace, I just got one for you. I added it as a second file to the above gist. As you'll see, it's crashing in `libsane` trying to get a list of devices.

**Comment by sglass68** [comment]
Hi, 

OK, I've just updated master to correct this. Thank you for the report.

- Simon
