### ISSUE TITLE
Paperman core dumps when listing devices

### ISSUE THREAD

**Issue by chuckremes** [sglass68/paperman#12]
Pulled latest master and built. Still get a core dump.

OS: Ubuntu 16.10
`Linux remes-linux 4.8.0-39-generic #42-Ubuntu SMP Mon Feb 20 11:47:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

What did I do?
I built paperman from current master (258779c748cec) according to INSTALL instructions. Ran ./paperman. Clicked on "Perform a scan immediately using current settings" which brought up a dialog box to pick a device. I first clicked on "select all devices" which core dumped. I then reran and tried "select local devices" and it cored too.

Here's a gist of the gdb backtrace.

https://gist.github.com/chuckremes/0fba331cdd07aa09913b512ffd6bd1fd

**Comment by sglass68** [comment]
OK I have repeated this properly this time.

I will take a look. In the meantime you don't need to click that button as it doesn't really do anything very useful.

**Comment by sglass68** [comment]
OK I think I found this. It was a problem with the way the simulated scanner was handled.

Fixed in:

4daa248 qscanner: Avoid messing with sane's scanner table
