### ISSUE TITLE
Packet libpoppler-qt4-dev can not be found

### ISSUE THREAD

**Issue by res55** [sglass68/paperman#18]
I need access to my old paperport-.max files and wanted to use paperman for this.

On my Ubuntu18.04 PC I wanted to install this:

`sudo apt-get install libpoppler-qt4-dev

Paketlisten werden gelesen... Fertig

Abhängigkeitsbaum wird aufgebaut.       

Statusinformationen werden eingelesen.... Fertig

E: Paket libpoppler-qt4-dev kann nicht gefunden werden.`

but got the answer: not found.

Has anybody a hint for me, how to succeed?

Andreas

**Comment by sglass68** [comment]
Hi,

You should be able to install libpoppler-qt5-dev instead.

Regards,
Simon
