### ISSUE TITLE
Relies on outdated QT4-core-2

### ISSUE THREAD

**Issue by Zakkumaru** [sglass68/paperman#19]
It would be more convenient, and frankly easier to compile, if it would use libpoppler-qt4-4, instead of libpoppler-qt4-2.

The real dead end I'm facing is getting libqt4-core to install.  However, this is all really stemming from this project being a bit outdated.  I would just like to be able to open .max files on Linux.  I can't even get PaperPort from the manufacturer's website, any longer.

**Comment by sglass68** [comment]
Hi,

I think you need to try to build it again.

For me it is using QT5:

ldd paperman |grep libpop
	libpoppler-qt5.so.1 => /usr/lib/x86_64-linux-gnu/libpoppler-qt5.so.1 (0x00007f1d25afc000)
	libpoppler.so.73 => /usr/lib/x86_64-linux-gnu/libpoppler.so.73 (0x00007f1d21ea5000)

The commit you should be building is:

de04c76 (HEAD -> dev, origin/master) Merge pull request #16 from Hum4n01d/master

The project was ported to QT5 a few years back, e.g. see this:

commit 9ca2a5f73459c95fbb427578c06167fd5775e354
Author: Simon Glass <sjg@chromium.org>
Date:   Thu Mar 9 21:23:55 2017 -0700

    Bring in correct poppler libraries for qt4/5

 paperman.pro | 11 +++++++++--
 pdfio.h      |  4 ++++
 2 files changed, 13 insertions(+), 2 deletions(-)

Regards,
Simon

**Comment by sglass68** [comment]
I assume this is resolved.
