### ISSUE TITLE
Command line options

### ISSUE THREAD

**Issue by gsfjim** [sglass68/paperman#21]
I have compiled and run paperman and the gui works fine. I have a lot of paperport .max files to convert to pdf and batch processing would be very useful. Invoking with "paperman --help" returns directions for running "maxview" from the command line, but my understanding is that paperman is the new maxview. Invoking with "paperman -p blah.max blah.pdf" returns "invalid option -p" . Running maxview returns "command not found"

Have the command line options been removed from paperman? 

Thanks,
Jim

**Comment by sglass68** [comment]
Hi,

Unfortunately the command-line options were disabled some years ago and for some reason I never got around to enabling them.

One possible option is to put them all in the same directory, select them and press Ctrl-Shift-P to convert to PDF?

Regards,
Simon

**Comment by gsfjim** [comment]
That works perfectly. 

Thanks!
Jim
