### ISSUE TITLE
git fails:  Could not read from remote repository

### ISSUE THREAD

**Issue by bshanteau** [sglass68/paperman#4]
I am trying to follow your instructions here to compile paperman in Linux Mint 17.1:
<https://github.com/sglass68/paperman/wiki/Paperman-cross-platform-paper-mangement-like-PaperPort,-was-maxview>

The prerequisites installed OK, but this git command did not work:

>$ git clone git@github.com:sglass68/paperman.git
Cloning into 'paperman'...
Permission denied (publickey).
fatal: Could not read from remote repository.

>Please make sure you have the correct access rights and the repository exists.

What do I need to do?

**Comment by bshanteau** [comment]
The git line in your instructions should be:
>$ git clone git://github.com/sglass68/paperman paperman

And the command to run paperman should be:
>$./paperman /path/to/paper

**Comment by sglass68** [comment]
OK thanks, I fixed it.

- Simon

**Comment by bshanteau** [comment]
I hope you don't mind that I edited the instructions here: https://github.com/sglass68/paperman/wiki/Paperman-cross-platform-paper-mangement-like-PaperPort,-was-maxview

I deleted duplicate entries in the pre-requisites and added g++ and libpodofo-dev.

I installed each of the pre-requisites using the Software Manager gui and it compiled OK.

I can run paperman in Linux Mint 17.1 now, but when I try to drop a file into the files area, the program quits and drops back to the terminal.

Also, trying to OCR a max file gives me an error message that tessaract is not found. I installed tesseract-ocr and tesseract-ocr-eng, but now I get an error message saying, "Maxview: Could not execute 'convert'".

BTW, where do you want us to post bugs reports like these?

**Comment by sglass68** [comment]
Hi,

Looks like you have found the issue tracker. It is here:

https://github.com/sglass68/paperman/issues

- Simon
