### ISSUE TITLE
OCR error: "Maxview: Could not execute 'convert'"

### ISSUE THREAD

**Issue by bshanteau** [sglass68/paperman#7]
Trying to OCR a max file gives me an error message that tessaract is not found. I installed tesseract-ocr and tesseract-ocr-eng, but now I get an error message saying, "Maxview: Could not execute 'convert'".

**Comment by sglass68** [comment]
Hi,

If you type 'convert' it might tell you the package to install. For me it
is:

sudo apt-get install imagemagick

Regards,
Simon

**Comment by bshanteau** [comment]
In that case, shouldn't these files be added to the pre-requisites to enable the OCR feature of Paperman?
>tesseract-ocr, tesseract-ocr-eng imagemagick

**Comment by sglass68** [comment]
I have updated the instructions to say that.
