### ISSUE TITLE
QT3 no longer used in modern Linux distros, unable to build

### ISSUE THREAD

**Issue by minakitty** [sglass68/paperman#8]
INSTALL states:
"Ensure you have libqt3-dev installed"

but apt-get reports "Package libqt3-dev is not available, but is referred to by another package. This may mean that the package is missing, has been obsoleted, or is only available from another source".  Further research shows that QT3 has been obsoleted in Ubuntu for some time now, since the introduction of QT5.  An attempt to force qmake and make gave me the following output:

heatheriac@Kaname ~/paperman $ qmake
Project MESSAGE: Type 'make' to build paperman
Project ERROR: Unknown module(s) in QT: qt3support
heatheriac@Kaname ~/paperman $ make
make: **\* No targets specified and no makefile found.  Stop.

**Comment by sglass68** [comment]
Hi,

There is some residual use of Qt3 that needs cleaning up. I will see what I
can do. Help appreciated!

- Simon

**Comment by minakitty** [comment]
As much as I'd love to be able to help, I don't know enough of the coding syntax to be useful.  I can usually just help hunt down bugs

**Comment by Hum4n01d** [comment]
@sglass68 Any news?

**Comment by sglass68** [comment]
No news from me, although it's preventing me from upgrading so I'll find the time before too long...

**Comment by Hum4n01d** [comment]
@sglass68 I’d like to use the paperman app but I don’t know how to install it on my Mac

**Comment by sglass68** [comment]
TBH neither do I. It was ported by someone at one point but I was unable to replicate it, instead getting lost in the complexities of Xcode, etc. I don't use Macs much, but in principle it should work since it uses QT.

**Comment by Hum4n01d** [comment]
@sglass68 In that case, do you have any recommendations on how to convert .max files to .pdfs without paperman?

**Comment by sglass68** [comment]
Perhaps use a virtual machine to run Linux on your Mac?

http://www.simplehelp.net/2015/06/09/how-to-install-ubuntu-on-your-mac/

**Comment by sglass68** [comment]
The port to QT4 is complete now.
