### ISSUE TITLE
Installing on macOS Sierra

### ISSUE THREAD

**Issue by Hum4n01d** [sglass68/paperman#9]
Hi @sglass68,

I’m interested in using this app to convert some .max files to .pdfs but I’m clueless as to compiling it on my computer. It would be helpful to have installation instructions.

Thanks!
@hum4n01d

**Comment by Hum4n01d** [comment]
Oh wait I just found the INSTALL file let me try this out

**Comment by Hum4n01d** [comment]
Well that didn’t help, I don’t know what `libqt3-dev` is or how to install it

**Comment by Hum4n01d** [comment]
I still need to convert `.max`s to `.pdf`s :)

**Comment by sglass68** [comment]
The problem might be that your distribution does not support libqt3-dev. This is QT version 3 and is quite old now. Version 4 is a major change and quite a lot of work to port.

I've just finished porting this, so you could perhaps clone it and try again.

**Comment by sglass68** [comment]
Actually I see that you are using Mac OS. I'm sorry but I have not tried compiling it on Mac OS. I am sure it would need a bit of work. I found the Xcode thing really confusing when I tried a few years ago.

If you know a Mac programmer then maybe they could have a try?

- Simon
